// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using W9.D2.EFCRUD.DataLayer;

#nullable disable

namespace W9.D2.EFCRUD.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20240730085225_StartManagement")]
    partial class StartManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<int>("ArticlesId")
                        .HasColumnType("int");

                    b.Property<string>("TagsText")
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("ArticlesId", "TagsText");

                    b.HasIndex("TagsText");

                    b.ToTable("ArticleTag");
                });

            modelBuilder.Entity("CommentTag", b =>
                {
                    b.Property<int>("CommentsId")
                        .HasColumnType("int");

                    b.Property<string>("TagsText")
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("CommentsId", "TagsText");

                    b.HasIndex("TagsText");

                    b.ToTable("CommentTag");
                });

            modelBuilder.Entity("PictureTag", b =>
                {
                    b.Property<int>("PicturesId")
                        .HasColumnType("int");

                    b.Property<string>("TagsText")
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("PicturesId", "TagsText");

                    b.HasIndex("TagsText");

                    b.ToTable("PictureTag");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "tommie@mayert.ca",
                            FriendlyName = "Madison Beahan",
                            Password = "password"
                        },
                        new
                        {
                            Id = 2,
                            Email = "arnold@starkemmerich.info",
                            FriendlyName = "Prof. Zella Nolan",
                            Password = "password"
                        },
                        new
                        {
                            Id = 3,
                            Email = "dax_predovic@tillman.us",
                            FriendlyName = "Gabe McGlynn",
                            Password = "password"
                        },
                        new
                        {
                            Id = 4,
                            Email = "chyna@huels.name",
                            FriendlyName = "Mr. Rubye Willms",
                            Password = "password"
                        },
                        new
                        {
                            Id = 5,
                            Email = "lance.dicki@schamberger.us",
                            FriendlyName = "Mr. Agustina Kreiger",
                            Password = "password"
                        },
                        new
                        {
                            Id = 6,
                            Email = "jermaine.mclaughlin@kunde.name",
                            FriendlyName = "Rahul Wyman",
                            Password = "password"
                        },
                        new
                        {
                            Id = 7,
                            Email = "olin@erdmanreichel.uk",
                            FriendlyName = "Katlyn Cummerata",
                            Password = "password"
                        },
                        new
                        {
                            Id = 8,
                            Email = "bartholome@littlekautzer.us",
                            FriendlyName = "Eloisa Kirlin",
                            Password = "password"
                        },
                        new
                        {
                            Id = 9,
                            Email = "joannie@kutch.uk",
                            FriendlyName = "Jarret Lynch",
                            Password = "password"
                        },
                        new
                        {
                            Id = 10,
                            Email = "brendan@kuhlman.us",
                            FriendlyName = "Kari Bradtke",
                            Password = "password"
                        },
                        new
                        {
                            Id = 11,
                            Email = "sabryna.rolfson@pfeffermonahan.co.uk",
                            FriendlyName = "Wellington Ratke",
                            Password = "password"
                        },
                        new
                        {
                            Id = 12,
                            Email = "scot.haag@strosin.name",
                            FriendlyName = "Heath Kshlerin",
                            Password = "password"
                        },
                        new
                        {
                            Id = 13,
                            Email = "colt_lynch@russel.ca",
                            FriendlyName = "Mr. Kamron Amara Turcotte",
                            Password = "password"
                        },
                        new
                        {
                            Id = 14,
                            Email = "kurt@sauer.co.uk",
                            FriendlyName = "Lorenza Rempel",
                            Password = "password"
                        },
                        new
                        {
                            Id = 15,
                            Email = "fredy@bodemcclure.us",
                            FriendlyName = "America Becker",
                            Password = "password"
                        },
                        new
                        {
                            Id = 16,
                            Email = "caroline@oconnerfahey.ca",
                            FriendlyName = "Mr. Josiane Shanahan",
                            Password = "password"
                        },
                        new
                        {
                            Id = 17,
                            Email = "marcelina_skiles@hegmann.name",
                            FriendlyName = "Luther Farrell",
                            Password = "password"
                        },
                        new
                        {
                            Id = 18,
                            Email = "rudy@dubuqueshanahan.co.uk",
                            FriendlyName = "Ms. Alexandro Franz Towne MD",
                            Password = "password"
                        },
                        new
                        {
                            Id = 19,
                            Email = "tierra.parker@cronin.info",
                            FriendlyName = "Cyrus Veum",
                            Password = "password"
                        },
                        new
                        {
                            Id = 20,
                            Email = "kelsi@keeling.co.uk",
                            FriendlyName = "Cyril Schinner",
                            Password = "password"
                        },
                        new
                        {
                            Id = 21,
                            Email = "gabriel.haley@quigleyhickle.uk",
                            FriendlyName = "Dr. Isaias Schinner DVM",
                            Password = "password"
                        },
                        new
                        {
                            Id = 22,
                            Email = "morton_renner@voncartwright.ca",
                            FriendlyName = "Mrs. Cruz Cremin IV",
                            Password = "password"
                        },
                        new
                        {
                            Id = 23,
                            Email = "francesca_schuster@daniel.co.uk",
                            FriendlyName = "Dr. Spencer Rath",
                            Password = "password"
                        },
                        new
                        {
                            Id = 24,
                            Email = "sammy_funk@armstrong.com",
                            FriendlyName = "Ansel Braun",
                            Password = "password"
                        },
                        new
                        {
                            Id = 25,
                            Email = "phoebe_lakin@reichel.name",
                            FriendlyName = "Prof. Pearline Volkman",
                            Password = "password"
                        },
                        new
                        {
                            Id = 26,
                            Email = "orion@considineschamberger.biz",
                            FriendlyName = "Dr. Roma Keebler",
                            Password = "password"
                        },
                        new
                        {
                            Id = 27,
                            Email = "alysson@daugherty.info",
                            FriendlyName = "Dr. Marta Emard I",
                            Password = "password"
                        },
                        new
                        {
                            Id = 28,
                            Email = "jude.heidenreich@ruecker.name",
                            FriendlyName = "Scotty Ledner",
                            Password = "password"
                        },
                        new
                        {
                            Id = 29,
                            Email = "leila.schmeler@mertz.com",
                            FriendlyName = "Mrs. Delta Schuyler Buckridge",
                            Password = "password"
                        },
                        new
                        {
                            Id = 30,
                            Email = "jarrod.satterfield@schumm.info",
                            FriendlyName = "Griffin Bednar",
                            Password = "password"
                        },
                        new
                        {
                            Id = 31,
                            Email = "helga_mcclure@bruen.biz",
                            FriendlyName = "Clementine Heaney",
                            Password = "password"
                        },
                        new
                        {
                            Id = 32,
                            Email = "monique.anderson@rueckerhilll.ca",
                            FriendlyName = "Prof. Layla King",
                            Password = "password"
                        },
                        new
                        {
                            Id = 33,
                            Email = "xavier@gislason.info",
                            FriendlyName = "Hilton Okuneva",
                            Password = "password"
                        },
                        new
                        {
                            Id = 34,
                            Email = "gerard@kuhic.co.uk",
                            FriendlyName = "Stefanie Crona",
                            Password = "password"
                        },
                        new
                        {
                            Id = 35,
                            Email = "johnathon@mcglynncrist.name",
                            FriendlyName = "Jerel Hoeger",
                            Password = "password"
                        },
                        new
                        {
                            Id = 36,
                            Email = "layla@greenholtpadberg.ca",
                            FriendlyName = "Cara Darrick McDermott DVM",
                            Password = "password"
                        },
                        new
                        {
                            Id = 37,
                            Email = "dalton.waters@rau.ca",
                            FriendlyName = "Jaquan Gaylord",
                            Password = "password"
                        },
                        new
                        {
                            Id = 38,
                            Email = "candace@zboncak.com",
                            FriendlyName = "Emelie Wiegand",
                            Password = "password"
                        },
                        new
                        {
                            Id = 39,
                            Email = "angeline_bradtke@carroll.uk",
                            FriendlyName = "Richie Herman",
                            Password = "password"
                        },
                        new
                        {
                            Id = 40,
                            Email = "freeman@abernathyondricka.info",
                            FriendlyName = "Mrs. Ashton Konopelski",
                            Password = "password"
                        },
                        new
                        {
                            Id = 41,
                            Email = "mertie.watsica@gibson.ca",
                            FriendlyName = "Euna Morar",
                            Password = "password"
                        },
                        new
                        {
                            Id = 42,
                            Email = "reilly_legros@hane.uk",
                            FriendlyName = "Ms. Grayson Aiden Sawayn",
                            Password = "password"
                        },
                        new
                        {
                            Id = 43,
                            Email = "trudie@pfannerstill.ca",
                            FriendlyName = "Jaren Frami",
                            Password = "password"
                        },
                        new
                        {
                            Id = 44,
                            Email = "adelle_rogahn@klockomiller.biz",
                            FriendlyName = "Mr. Travon Nia Mann",
                            Password = "password"
                        },
                        new
                        {
                            Id = 45,
                            Email = "rebecca@orn.us",
                            FriendlyName = "Dr. Cristina Senger",
                            Password = "password"
                        },
                        new
                        {
                            Id = 46,
                            Email = "zelda.wisozk@hilll.us",
                            FriendlyName = "Samanta Fahey",
                            Password = "password"
                        },
                        new
                        {
                            Id = 47,
                            Email = "rhiannon.rodriguez@cartwright.ca",
                            FriendlyName = "Mr. Tyrell Kirsten Hand",
                            Password = "password"
                        },
                        new
                        {
                            Id = 48,
                            Email = "barney@stehr.biz",
                            FriendlyName = "Mrs. Else Feest MD",
                            Password = "password"
                        },
                        new
                        {
                            Id = 49,
                            Email = "dario_skiles@towne.name",
                            FriendlyName = "Daphne Beahan MD",
                            Password = "password"
                        },
                        new
                        {
                            Id = 50,
                            Email = "lyla_roob@dach.biz",
                            FriendlyName = "Coy Wintheiser",
                            Password = "password"
                        },
                        new
                        {
                            Id = 51,
                            Email = "imogene@hauck.info",
                            FriendlyName = "Bret Crist",
                            Password = "password"
                        },
                        new
                        {
                            Id = 52,
                            Email = "betty@considine.biz",
                            FriendlyName = "Jewel Rosenbaum",
                            Password = "password"
                        },
                        new
                        {
                            Id = 53,
                            Email = "taylor@murray.us",
                            FriendlyName = "Mrs. Johanna Witting",
                            Password = "password"
                        },
                        new
                        {
                            Id = 54,
                            Email = "devan@daugherty.co.uk",
                            FriendlyName = "Ms. Zackery Bergnaum Jr.",
                            Password = "password"
                        },
                        new
                        {
                            Id = 55,
                            Email = "fanny@rueckerdavis.uk",
                            FriendlyName = "Carmella Halvorson",
                            Password = "password"
                        },
                        new
                        {
                            Id = 56,
                            Email = "reid.feeney@gloverernser.us",
                            FriendlyName = "Mr. Anne Efrain Nolan",
                            Password = "password"
                        },
                        new
                        {
                            Id = 57,
                            Email = "marilie@ward.biz",
                            FriendlyName = "Loraine Wintheiser",
                            Password = "password"
                        },
                        new
                        {
                            Id = 58,
                            Email = "florida@marquardtarmstrong.biz",
                            FriendlyName = "Cassidy Hauck",
                            Password = "password"
                        },
                        new
                        {
                            Id = 59,
                            Email = "rachael@simonis.co.uk",
                            FriendlyName = "Abigale Marques McLaughlin PhD",
                            Password = "password"
                        },
                        new
                        {
                            Id = 60,
                            Email = "oleta@cassin.name",
                            FriendlyName = "Felipa Lehner",
                            Password = "password"
                        },
                        new
                        {
                            Id = 61,
                            Email = "paxton@howe.com",
                            FriendlyName = "Mr. Sierra Goodwin",
                            Password = "password"
                        },
                        new
                        {
                            Id = 62,
                            Email = "haskell.crist@moorestracke.info",
                            FriendlyName = "Mr. Bianka Jaylen Weber",
                            Password = "password"
                        },
                        new
                        {
                            Id = 63,
                            Email = "margarete@langoshschulist.name",
                            FriendlyName = "Mr. Cleora Reta Murazik DVM",
                            Password = "password"
                        },
                        new
                        {
                            Id = 64,
                            Email = "donnell@aufderhar.info",
                            FriendlyName = "Lamar Kling",
                            Password = "password"
                        },
                        new
                        {
                            Id = 65,
                            Email = "dawn.bayer@rempel.ca",
                            FriendlyName = "Ms. Diana Jeramie Roberts",
                            Password = "password"
                        },
                        new
                        {
                            Id = 66,
                            Email = "filomena.brown@wilderman.ca",
                            FriendlyName = "Mr. Ernesto Nakia Bernier",
                            Password = "password"
                        },
                        new
                        {
                            Id = 67,
                            Email = "erling.weimann@king.us",
                            FriendlyName = "Mrs. Mabel Goldner",
                            Password = "password"
                        },
                        new
                        {
                            Id = 68,
                            Email = "laurel_murray@hegmann.biz",
                            FriendlyName = "Mireya Pollich",
                            Password = "password"
                        },
                        new
                        {
                            Id = 69,
                            Email = "zoila.gleason@leffler.uk",
                            FriendlyName = "Dr. Malcolm Lou Smith MD",
                            Password = "password"
                        },
                        new
                        {
                            Id = 70,
                            Email = "urban@dietrichstroman.uk",
                            FriendlyName = "Sarah Ernser",
                            Password = "password"
                        },
                        new
                        {
                            Id = 71,
                            Email = "skylar@haaghahn.ca",
                            FriendlyName = "Michale Hammes",
                            Password = "password"
                        },
                        new
                        {
                            Id = 72,
                            Email = "mathilde@dickinson.ca",
                            FriendlyName = "Orin Zemlak",
                            Password = "password"
                        },
                        new
                        {
                            Id = 73,
                            Email = "doyle@corwin.name",
                            FriendlyName = "Ms. Henri Jewess",
                            Password = "password"
                        },
                        new
                        {
                            Id = 74,
                            Email = "brenden.pacocha@terry.name",
                            FriendlyName = "Viola Ettie Schuppe I",
                            Password = "password"
                        },
                        new
                        {
                            Id = 75,
                            Email = "keshaun@hoeger.ca",
                            FriendlyName = "Noemi Gerda Windler III",
                            Password = "password"
                        },
                        new
                        {
                            Id = 76,
                            Email = "alexa@nicolas.info",
                            FriendlyName = "Augusta Kihn",
                            Password = "password"
                        },
                        new
                        {
                            Id = 77,
                            Email = "emmet@schmitt.com",
                            FriendlyName = "Ms. Justice Irwin Botsford",
                            Password = "password"
                        },
                        new
                        {
                            Id = 78,
                            Email = "tressa.howell@gutmannabbott.info",
                            FriendlyName = "Hellen Renner",
                            Password = "password"
                        },
                        new
                        {
                            Id = 79,
                            Email = "mason.rutherford@fahey.us",
                            FriendlyName = "Mr. Jacinthe Marvin V",
                            Password = "password"
                        },
                        new
                        {
                            Id = 80,
                            Email = "guy_jaskolski@wisozk.info",
                            FriendlyName = "Noe Rice",
                            Password = "password"
                        },
                        new
                        {
                            Id = 81,
                            Email = "madie_ortiz@green.biz",
                            FriendlyName = "Pauline Raynor",
                            Password = "password"
                        },
                        new
                        {
                            Id = 82,
                            Email = "pedro.hansen@kunde.info",
                            FriendlyName = "Ms. Monserrat Franz Harris",
                            Password = "password"
                        },
                        new
                        {
                            Id = 83,
                            Email = "elwin_okuneva@bashirian.name",
                            FriendlyName = "Prof. Pietro Langosh",
                            Password = "password"
                        },
                        new
                        {
                            Id = 84,
                            Email = "christ@jakubowski.uk",
                            FriendlyName = "Fredrick Becker",
                            Password = "password"
                        },
                        new
                        {
                            Id = 85,
                            Email = "marcel@eichmannzulauf.com",
                            FriendlyName = "Katrina Strosin",
                            Password = "password"
                        },
                        new
                        {
                            Id = 86,
                            Email = "trinity_heidenreich@stoltenbergkoch.com",
                            FriendlyName = "Wava Parisian",
                            Password = "password"
                        },
                        new
                        {
                            Id = 87,
                            Email = "kianna@schulistgoyette.ca",
                            FriendlyName = "Juston Brekke I",
                            Password = "password"
                        },
                        new
                        {
                            Id = 88,
                            Email = "rosina@flatley.biz",
                            FriendlyName = "Cordia Kris",
                            Password = "password"
                        },
                        new
                        {
                            Id = 89,
                            Email = "roxanne_brekke@donnellygoldner.com",
                            FriendlyName = "Zackary Leffler",
                            Password = "password"
                        },
                        new
                        {
                            Id = 90,
                            Email = "nicola@brakus.info",
                            FriendlyName = "Sherwood Joel Moen DDS",
                            Password = "password"
                        },
                        new
                        {
                            Id = 91,
                            Email = "michaela@johnstonmonahan.name",
                            FriendlyName = "Angelo Rath",
                            Password = "password"
                        },
                        new
                        {
                            Id = 92,
                            Email = "elvie_mckenzie@schmeler.com",
                            FriendlyName = "Obie Powlowski I",
                            Password = "password"
                        },
                        new
                        {
                            Id = 93,
                            Email = "patricia.cole@upton.biz",
                            FriendlyName = "Ms. Nolan Baumbach II",
                            Password = "password"
                        },
                        new
                        {
                            Id = 94,
                            Email = "gregg@prosaccocasper.us",
                            FriendlyName = "Prof. Enoch Lenora Reynolds V",
                            Password = "password"
                        },
                        new
                        {
                            Id = 95,
                            Email = "kelley@lockman.name",
                            FriendlyName = "Johann Hudson",
                            Password = "password"
                        },
                        new
                        {
                            Id = 96,
                            Email = "sandra.cartwright@padbergkemmer.ca",
                            FriendlyName = "Ludwig McGlynn",
                            Password = "password"
                        },
                        new
                        {
                            Id = 97,
                            Email = "vesta@kilbackking.us",
                            FriendlyName = "Dr. Ryan Dustin Tromp",
                            Password = "password"
                        },
                        new
                        {
                            Id = 98,
                            Email = "jovani_mraz@bergstrom.biz",
                            FriendlyName = "Hermina Langworth",
                            Password = "password"
                        },
                        new
                        {
                            Id = 99,
                            Email = "aiyana_vandervort@greenfelder.ca",
                            FriendlyName = "Antoinette Watsica",
                            Password = "password"
                        },
                        new
                        {
                            Id = 100,
                            Email = "solon@hettinger.name",
                            FriendlyName = "Shyann Walker",
                            Password = "password"
                        });
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("OriginalHeight")
                        .HasColumnType("int");

                    b.Property<int>("OriginalWidth")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Tag", b =>
                {
                    b.Property<string>("Text")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Text");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsText")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommentTag", b =>
                {
                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsText")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PictureTag", b =>
                {
                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Picture", null)
                        .WithMany()
                        .HasForeignKey("PicturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsText")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Article", b =>
                {
                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Author", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Comment", b =>
                {
                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Article", null)
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId");

                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Author", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Picture", b =>
                {
                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Article", null)
                        .WithMany("Pictures")
                        .HasForeignKey("ArticleId");

                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Author", null)
                        .WithMany("Pictures")
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Article", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Pictures");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Author", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");

                    b.Navigation("Pictures");
                });
#pragma warning restore 612, 618
        }
    }
}
