// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using W9.D2.EFCRUD.DataLayer;

#nullable disable

namespace W9.D2.EFCRUD.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20240730102404_AuthorsManagement")]
    partial class AuthorsManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<int>("ArticlesId")
                        .HasColumnType("int");

                    b.Property<string>("TagsText")
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("ArticlesId", "TagsText");

                    b.HasIndex("TagsText");

                    b.ToTable("ArticleTag");
                });

            modelBuilder.Entity("CommentTag", b =>
                {
                    b.Property<int>("CommentsId")
                        .HasColumnType("int");

                    b.Property<string>("TagsText")
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("CommentsId", "TagsText");

                    b.HasIndex("TagsText");

                    b.ToTable("CommentTag");
                });

            modelBuilder.Entity("PictureTag", b =>
                {
                    b.Property<int>("PicturesId")
                        .HasColumnType("int");

                    b.Property<string>("TagsText")
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("PicturesId", "TagsText");

                    b.HasIndex("TagsText");

                    b.ToTable("PictureTag");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "cleve_hirthe@carrollkirlin.info",
                            FriendlyName = "Eden Ryan Mann Sr.",
                            Password = "password"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lourdes@mcclure.biz",
                            FriendlyName = "Leila Kemmer",
                            Password = "password"
                        },
                        new
                        {
                            Id = 3,
                            Email = "delbert.koepp@schultzswift.co.uk",
                            FriendlyName = "Mrs. Baron Manuel Mraz DDS",
                            Password = "password"
                        },
                        new
                        {
                            Id = 4,
                            Email = "celia@jewesslittel.name",
                            FriendlyName = "Tanya Denesik V",
                            Password = "password"
                        },
                        new
                        {
                            Id = 5,
                            Email = "tianna@schoen.uk",
                            FriendlyName = "Miss Thomas Koss",
                            Password = "password"
                        },
                        new
                        {
                            Id = 6,
                            Email = "roman_mayert@dach.com",
                            FriendlyName = "Connor Koss I",
                            Password = "password"
                        },
                        new
                        {
                            Id = 7,
                            Email = "valerie@beahanpowlowski.co.uk",
                            FriendlyName = "Prof. Macy Renner DVM",
                            Password = "password"
                        },
                        new
                        {
                            Id = 8,
                            Email = "fletcher@buckridge.com",
                            FriendlyName = "Ms. Alva Mueller Jr.",
                            Password = "password"
                        },
                        new
                        {
                            Id = 9,
                            Email = "courtney_barton@cruickshankpredovic.com",
                            FriendlyName = "Mr. Triston Kub V",
                            Password = "password"
                        },
                        new
                        {
                            Id = 10,
                            Email = "ike_blick@bernhard.ca",
                            FriendlyName = "Green Kozey",
                            Password = "password"
                        },
                        new
                        {
                            Id = 11,
                            Email = "brandt@swaniawskigusikowski.us",
                            FriendlyName = "Loyce Ebert",
                            Password = "password"
                        },
                        new
                        {
                            Id = 12,
                            Email = "aniya@smithkris.co.uk",
                            FriendlyName = "Delphia Walker",
                            Password = "password"
                        },
                        new
                        {
                            Id = 13,
                            Email = "sharon_kohler@howe.name",
                            FriendlyName = "Dr. Maryam Skylar Boehm",
                            Password = "password"
                        },
                        new
                        {
                            Id = 14,
                            Email = "karlie.gibson@blick.com",
                            FriendlyName = "Ms. Leanna Gerlach Jr.",
                            Password = "password"
                        },
                        new
                        {
                            Id = 15,
                            Email = "howard.littel@gottlieb.info",
                            FriendlyName = "Lilliana Cole",
                            Password = "password"
                        },
                        new
                        {
                            Id = 16,
                            Email = "edgardo@quitzondicki.com",
                            FriendlyName = "Cristopher Bergnaum",
                            Password = "password"
                        },
                        new
                        {
                            Id = 17,
                            Email = "kieran.beer@oreilly.com",
                            FriendlyName = "Mr. Jonatan Glenna Spinka",
                            Password = "password"
                        },
                        new
                        {
                            Id = 18,
                            Email = "jonatan@krajcikbode.uk",
                            FriendlyName = "Dr. Chase Murl Raynor V",
                            Password = "password"
                        },
                        new
                        {
                            Id = 19,
                            Email = "caleb.dach@bartoletti.info",
                            FriendlyName = "Mr. Carlee Thaddeus Reichel",
                            Password = "password"
                        },
                        new
                        {
                            Id = 20,
                            Email = "gideon@ricegraham.uk",
                            FriendlyName = "Fernando McKenzie",
                            Password = "password"
                        },
                        new
                        {
                            Id = 21,
                            Email = "michelle@carter.name",
                            FriendlyName = "Roslyn Lueilwitz",
                            Password = "password"
                        },
                        new
                        {
                            Id = 22,
                            Email = "carlee@carter.biz",
                            FriendlyName = "Dr. Lewis Little",
                            Password = "password"
                        },
                        new
                        {
                            Id = 23,
                            Email = "isadore@mccullough.uk",
                            FriendlyName = "Leora Robel III",
                            Password = "password"
                        },
                        new
                        {
                            Id = 24,
                            Email = "justice@bergeprohaska.co.uk",
                            FriendlyName = "Oliver Wilkinson",
                            Password = "password"
                        },
                        new
                        {
                            Id = 25,
                            Email = "yadira_gusikowski@rohan.info",
                            FriendlyName = "Mr. Chet Morar",
                            Password = "password"
                        },
                        new
                        {
                            Id = 26,
                            Email = "paxton.hamill@emmerich.biz",
                            FriendlyName = "Oral Brown",
                            Password = "password"
                        },
                        new
                        {
                            Id = 27,
                            Email = "damon_weber@schneider.name",
                            FriendlyName = "Prof. Mia Casper",
                            Password = "password"
                        },
                        new
                        {
                            Id = 28,
                            Email = "leon@raynorcormier.us",
                            FriendlyName = "Fermin Haley",
                            Password = "password"
                        },
                        new
                        {
                            Id = 29,
                            Email = "fiona_cormier@howe.com",
                            FriendlyName = "Mr. Winnifred Schumm",
                            Password = "password"
                        },
                        new
                        {
                            Id = 30,
                            Email = "kelvin.heaney@bruenjaskolski.name",
                            FriendlyName = "Zane Harris",
                            Password = "password"
                        },
                        new
                        {
                            Id = 31,
                            Email = "palma@becker.co.uk",
                            FriendlyName = "Eliane Rau",
                            Password = "password"
                        },
                        new
                        {
                            Id = 32,
                            Email = "leland@lehner.info",
                            FriendlyName = "Ms. Lela Roob V",
                            Password = "password"
                        },
                        new
                        {
                            Id = 33,
                            Email = "manuela@lehnermayert.name",
                            FriendlyName = "Prof. Ahmed Felicia Bednar",
                            Password = "password"
                        },
                        new
                        {
                            Id = 34,
                            Email = "berniece@andersonbergnaum.name",
                            FriendlyName = "Gregorio Rolfson",
                            Password = "password"
                        },
                        new
                        {
                            Id = 35,
                            Email = "leonie.pagac@pfannerstill.info",
                            FriendlyName = "Jewel Klein",
                            Password = "password"
                        },
                        new
                        {
                            Id = 36,
                            Email = "willis.durgan@conroyborer.name",
                            FriendlyName = "Prof. Davin Celine McClure",
                            Password = "password"
                        },
                        new
                        {
                            Id = 37,
                            Email = "jany.ledner@mohrdouglas.co.uk",
                            FriendlyName = "Ms. Jayde Stark V",
                            Password = "password"
                        },
                        new
                        {
                            Id = 38,
                            Email = "kasey.becker@runte.biz",
                            FriendlyName = "Mr. Haleigh Bashirian DVM",
                            Password = "password"
                        },
                        new
                        {
                            Id = 39,
                            Email = "zelda@russel.ca",
                            FriendlyName = "Mr. Cleora Raymond Rutherford",
                            Password = "password"
                        },
                        new
                        {
                            Id = 40,
                            Email = "richie@greenfelder.us",
                            FriendlyName = "Quinn Effertz",
                            Password = "password"
                        },
                        new
                        {
                            Id = 41,
                            Email = "constantin.weissnat@kozeykoss.biz",
                            FriendlyName = "Savanna Grady",
                            Password = "password"
                        },
                        new
                        {
                            Id = 42,
                            Email = "herbert@steuberhudson.info",
                            FriendlyName = "Madeline Willms",
                            Password = "password"
                        },
                        new
                        {
                            Id = 43,
                            Email = "tracy.huels@nitzschekiehn.uk",
                            FriendlyName = "Leonor Jaskolski",
                            Password = "password"
                        },
                        new
                        {
                            Id = 44,
                            Email = "sophia.littel@treutel.name",
                            FriendlyName = "Beth Effie Mraz DDS",
                            Password = "password"
                        },
                        new
                        {
                            Id = 45,
                            Email = "kyra.schaden@hermiston.biz",
                            FriendlyName = "Tom Bosco",
                            Password = "password"
                        },
                        new
                        {
                            Id = 46,
                            Email = "minnie@kiehnhettinger.us",
                            FriendlyName = "Kasandra Hilll",
                            Password = "password"
                        },
                        new
                        {
                            Id = 47,
                            Email = "raven.bailey@wolf.biz",
                            FriendlyName = "Mr. Geovanny Loren Nolan DVM",
                            Password = "password"
                        },
                        new
                        {
                            Id = 48,
                            Email = "zander@runolfsson.name",
                            FriendlyName = "Jaren Rippin DDS",
                            Password = "password"
                        },
                        new
                        {
                            Id = 49,
                            Email = "kenyatta_klein@collier.co.uk",
                            FriendlyName = "Orion Abbott",
                            Password = "password"
                        },
                        new
                        {
                            Id = 50,
                            Email = "meredith_turcotte@bahringer.uk",
                            FriendlyName = "Myrtice Murazik",
                            Password = "password"
                        },
                        new
                        {
                            Id = 51,
                            Email = "maverick@heidenreich.com",
                            FriendlyName = "Alden Gleichner DDS",
                            Password = "password"
                        },
                        new
                        {
                            Id = 52,
                            Email = "allen@jacobson.co.uk",
                            FriendlyName = "Ralph O'Hara",
                            Password = "password"
                        },
                        new
                        {
                            Id = 53,
                            Email = "lauryn@aufderharshanahan.biz",
                            FriendlyName = "Sofia Jillian Green PhD",
                            Password = "password"
                        },
                        new
                        {
                            Id = 54,
                            Email = "daryl_walter@wymanhansen.name",
                            FriendlyName = "Daisha Bosco",
                            Password = "password"
                        },
                        new
                        {
                            Id = 55,
                            Email = "nelda_dibbert@huels.uk",
                            FriendlyName = "Mauricio Ritchie",
                            Password = "password"
                        },
                        new
                        {
                            Id = 56,
                            Email = "antonetta_steuber@luettgen.com",
                            FriendlyName = "Germaine Reinger DDS",
                            Password = "password"
                        },
                        new
                        {
                            Id = 57,
                            Email = "jillian@okeefe.us",
                            FriendlyName = "Giovanna Schoen Sr.",
                            Password = "password"
                        },
                        new
                        {
                            Id = 58,
                            Email = "danial.breitenberg@paucek.com",
                            FriendlyName = "Reed Aufderhar",
                            Password = "password"
                        },
                        new
                        {
                            Id = 59,
                            Email = "myrna_ferry@schiller.uk",
                            FriendlyName = "Emilia Hudson",
                            Password = "password"
                        },
                        new
                        {
                            Id = 60,
                            Email = "delphine_zboncak@von.name",
                            FriendlyName = "Celestine Ondricka",
                            Password = "password"
                        },
                        new
                        {
                            Id = 61,
                            Email = "burley@predovic.biz",
                            FriendlyName = "Miss Aurelia Vincenzo McCullough",
                            Password = "password"
                        },
                        new
                        {
                            Id = 62,
                            Email = "silas.rolfson@gislasonstiedemann.name",
                            FriendlyName = "Helena Horacio Hettinger IV",
                            Password = "password"
                        },
                        new
                        {
                            Id = 63,
                            Email = "brandt@armstrongratke.uk",
                            FriendlyName = "Mr. Brianne Krajcik",
                            Password = "password"
                        },
                        new
                        {
                            Id = 64,
                            Email = "libby_muller@auer.ca",
                            FriendlyName = "Mr. Ricky Melvina Weimann",
                            Password = "password"
                        },
                        new
                        {
                            Id = 65,
                            Email = "hermann@schummschaefer.info",
                            FriendlyName = "Ms. Tyreek Bradtke",
                            Password = "password"
                        },
                        new
                        {
                            Id = 66,
                            Email = "howard@kessler.name",
                            FriendlyName = "Prof. Samara Jaunita Herman II",
                            Password = "password"
                        },
                        new
                        {
                            Id = 67,
                            Email = "bertram@altenwerth.info",
                            FriendlyName = "Mrs. Willie Velma Schuster I",
                            Password = "password"
                        },
                        new
                        {
                            Id = 68,
                            Email = "isaac.marvin@stiedemann.co.uk",
                            FriendlyName = "Nelda Adams III",
                            Password = "password"
                        },
                        new
                        {
                            Id = 69,
                            Email = "kariane_corwin@bergstrom.name",
                            FriendlyName = "Dr. Else Viola Jewess Jr.",
                            Password = "password"
                        },
                        new
                        {
                            Id = 70,
                            Email = "alysson.renner@grady.name",
                            FriendlyName = "Prof. Sandy Queen Reichert",
                            Password = "password"
                        },
                        new
                        {
                            Id = 71,
                            Email = "abbey@herman.name",
                            FriendlyName = "Rocio Schroeder",
                            Password = "password"
                        },
                        new
                        {
                            Id = 72,
                            Email = "monique.wintheiser@bode.ca",
                            FriendlyName = "Clementina Huel",
                            Password = "password"
                        },
                        new
                        {
                            Id = 73,
                            Email = "gust@mueller.com",
                            FriendlyName = "Mr. Augustine Dach V",
                            Password = "password"
                        },
                        new
                        {
                            Id = 74,
                            Email = "madeline@kozey.co.uk",
                            FriendlyName = "Mrs. Forest Bogan Jr.",
                            Password = "password"
                        },
                        new
                        {
                            Id = 75,
                            Email = "godfrey@mante.biz",
                            FriendlyName = "Mr. Mylene Feil Jr.",
                            Password = "password"
                        },
                        new
                        {
                            Id = 76,
                            Email = "keely_powlowski@halvorsonsteuber.ca",
                            FriendlyName = "Ms. Eric Justice Carter I",
                            Password = "password"
                        },
                        new
                        {
                            Id = 77,
                            Email = "lila@feil.com",
                            FriendlyName = "Travis Osinski II",
                            Password = "password"
                        },
                        new
                        {
                            Id = 78,
                            Email = "jared@hamillcrona.info",
                            FriendlyName = "Vincenzo Lynch",
                            Password = "password"
                        },
                        new
                        {
                            Id = 79,
                            Email = "benjamin@langosh.name",
                            FriendlyName = "Dolly Hills",
                            Password = "password"
                        },
                        new
                        {
                            Id = 80,
                            Email = "carmelo@oreilly.ca",
                            FriendlyName = "Dr. Judd Letha Kihn Sr.",
                            Password = "password"
                        },
                        new
                        {
                            Id = 81,
                            Email = "isaiah.schimmel@rolfson.us",
                            FriendlyName = "Norris Dicki PhD",
                            Password = "password"
                        },
                        new
                        {
                            Id = 82,
                            Email = "jadyn@champlinbeier.co.uk",
                            FriendlyName = "Caleb Murphy",
                            Password = "password"
                        },
                        new
                        {
                            Id = 83,
                            Email = "marlene@brakusgoodwin.ca",
                            FriendlyName = "Mr. Katelynn Hills",
                            Password = "password"
                        },
                        new
                        {
                            Id = 84,
                            Email = "jessyca@goyette.uk",
                            FriendlyName = "Ardith Bins",
                            Password = "password"
                        },
                        new
                        {
                            Id = 85,
                            Email = "ole_blanda@feilcarroll.name",
                            FriendlyName = "Christina Baumbach",
                            Password = "password"
                        },
                        new
                        {
                            Id = 86,
                            Email = "sammie@wolffschuppe.uk",
                            FriendlyName = "Esta Amara Bogan Jr.",
                            Password = "password"
                        },
                        new
                        {
                            Id = 87,
                            Email = "adrienne@yundt.name",
                            FriendlyName = "Emelia Kohler",
                            Password = "password"
                        },
                        new
                        {
                            Id = 88,
                            Email = "doyle@brakus.ca",
                            FriendlyName = "Jordi Rice",
                            Password = "password"
                        },
                        new
                        {
                            Id = 89,
                            Email = "leda.muller@schowalterleffler.co.uk",
                            FriendlyName = "Keegan Baumbach",
                            Password = "password"
                        },
                        new
                        {
                            Id = 90,
                            Email = "roderick@streichruecker.us",
                            FriendlyName = "Adrianna Carroll DDS",
                            Password = "password"
                        },
                        new
                        {
                            Id = 91,
                            Email = "axel@roberts.ca",
                            FriendlyName = "Destiney Johnston",
                            Password = "password"
                        },
                        new
                        {
                            Id = 92,
                            Email = "mazie@ziemann.name",
                            FriendlyName = "Juana Bartell Jr.",
                            Password = "password"
                        },
                        new
                        {
                            Id = 93,
                            Email = "deborah@cole.ca",
                            FriendlyName = "Miss Cooper Ewell Dibbert DDS",
                            Password = "password"
                        },
                        new
                        {
                            Id = 94,
                            Email = "otis@hicklewisozk.name",
                            FriendlyName = "Wilma Rosenbaum",
                            Password = "password"
                        },
                        new
                        {
                            Id = 95,
                            Email = "agnes@kemmer.name",
                            FriendlyName = "Haleigh Sawayn PhD",
                            Password = "password"
                        },
                        new
                        {
                            Id = 96,
                            Email = "jeffry@huel.name",
                            FriendlyName = "Prof. Ashlynn Carroll V",
                            Password = "password"
                        },
                        new
                        {
                            Id = 97,
                            Email = "geraldine_hodkiewicz@fritschsporer.us",
                            FriendlyName = "Dr. Maryse Smith I",
                            Password = "password"
                        },
                        new
                        {
                            Id = 98,
                            Email = "elwyn_huel@kshlerin.info",
                            FriendlyName = "Freda Wilkinson",
                            Password = "password"
                        },
                        new
                        {
                            Id = 99,
                            Email = "josh_bogisich@kerlukekuhic.co.uk",
                            FriendlyName = "Mrs. Jeramie Conner Wolf",
                            Password = "password"
                        },
                        new
                        {
                            Id = 100,
                            Email = "danial_rippin@jacobsonheathcote.co.uk",
                            FriendlyName = "Dr. Phyllis Joe Rempel PhD",
                            Password = "password"
                        });
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("OriginalHeight")
                        .HasColumnType("int");

                    b.Property<int>("OriginalWidth")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Tag", b =>
                {
                    b.Property<string>("Text")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Text");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsText")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommentTag", b =>
                {
                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsText")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PictureTag", b =>
                {
                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Picture", null)
                        .WithMany()
                        .HasForeignKey("PicturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsText")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Article", b =>
                {
                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Author", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Comment", b =>
                {
                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Article", null)
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId");

                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Author", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Picture", b =>
                {
                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Article", null)
                        .WithMany("Pictures")
                        .HasForeignKey("ArticleId");

                    b.HasOne("W9.D2.EFCRUD.DataLayer.Entities.Author", null)
                        .WithMany("Pictures")
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Article", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Pictures");
                });

            modelBuilder.Entity("W9.D2.EFCRUD.DataLayer.Entities.Author", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");

                    b.Navigation("Pictures");
                });
#pragma warning restore 612, 618
        }
    }
}
