CREATE TABLE [dbo].[Users] (
    [Id]       INT            IDENTITY (1, 1) NOT NULL,
    [Username] NVARCHAR (20)  NOT NULL,
    [Password] NVARCHAR (128) NOT NULL,
	Birthday DATETIME2 ,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    UNIQUE NONCLUSTERED ([Username] ASC)
);
CREATE TABLE [dbo].Roles
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Name NVARCHAR(20) NOT NULL UNIQUE
)
CREATE TABLE [dbo].UsersRoles
(
	UserId INT NOT NULL,
	RoleId INT NOT NULL, 
    CONSTRAINT [PK_UserRoles] 
		PRIMARY KEY ([UserId], [RoleId])
)
CREATE TABLE [dbo].Customers
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Discriminator INT NOT NULL,
	Address NVARCHAR(128) NOT NULL,
	City NVARCHAR(80) NOT NULL,
	Region NVARCHAR(10) NULL,
	PostalCode NVARCHAR(10) NOT NULL
)
CREATE TABLE [dbo].People
(
	[Id] INT NOT NULL PRIMARY KEY,
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	FiscalCode CHAR(16) NOT NULL UNIQUE
)
CREATE TABLE [dbo].Companies
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(80) NOT NULL,
	VatCode CHAR(11) NOT NULL UNIQUE
)
CREATE TABLE [dbo].Shippings
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	CustomerId INT NOT NULL,
	ShippingNo CHAR(24) NOT NULL UNIQUE,
	ShipDate DATETIME2 NOT NULL,
	Weight DECIMAL(18,2) NOT NULL,
	RecipientId INT NOT NULL,
	Freight DECIMAL(18,2) NOT NULL,
	DeliveryDate DATETIME2 NOT NULL
)
CREATE TABLE [dbo].ShippingsUpdates
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	ShippingId INT NOT NULL,
	UpdatedAt DATETIME2 NULL DEFAULT GETDATE(),
	Status INT NOT NULL,
	Description NVARCHAR(255) NULL
)
